// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
let requestIdCounter = 0;

// 生成唯一的 requestId
const generateRequestId = () => {
	requestIdCounter += 1;
	return requestIdCounter.toString();
};

// 在WebView中调用React Native方法
const callReactNativeMethod = (method, params, callback) => {
	// 生成唯一的 requestId
	const requestId = generateRequestId();
	// 发送消息给 React Native
	const message = {
		method: method,
		params: params,
		requestId: requestId,
	};
	window.ReactNativeWebView.postMessage(JSON.stringify(message));
	// 保存请求的回调函数
	window.rpcCallbacks = window.rpcCallbacks || {};
	window.rpcCallbacks[requestId] = e => callback(requestId, e);
};
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function JavaScript_action() {
	// BEGIN USER CODE
	return new Promise((resolve, reject) => {
		const h = setTimeout(() => { reject('timeout') }, 3000);

		callReactNativeMethod('callReactNativeMethod', null, (requestId, e) => {
			clearTimeout(h);
			delete window.rpcCallbacks[requestId];
			// alert(requestId)
			// alert(JSON.stringify(e))
			resolve(e.result);
		});
	});
	// END USER CODE
}
